### ISSUE TITLE
Serverless Error: Trying to populate non string value into a string for variable ${self:custom.stage}. Please make sure the value of the property is a string

### ISSUE THREAD

**Issue by b805rohit** [Fullstack-Serverless-GraphQL/fullstack-serverless-graphql-docs#107]
## Steps To Reproduce

Link to code example:

Title of post you're stuck on:

**Comment by b805rohit** [comment]
Serverless Error: Trying to populate non string value into a string for variable ${self:custom.stage}. Please make sure the value of the property is a string

**Comment by AmoDinho** [comment]
Hey @b805rohit  this usually means that `${self:custom.stage}` is not a string value wherever you're reading it from. 
Have you populated the value in Seed where you're supposed to add the environment variables?

**Comment by bluemagma612** [comment]
I had this too. In the serverless.yml file  if you only include the `resources` provided in the example code, removing the default ones put there by the serverless installation, then the error should go away

**Comment by joseph-farruggio** [comment]
> Hey @b805rohit this usually means that `${self:custom.stage}` is not a string value wherever you're reading it from.
> Have you populated the value in Seed where you're supposed to add the environment variables?

Hey @AmoDinho - I'm having the same issue. What environment variables are supposed to be set in Seed? That wasn't covered in the tutorial.

**Comment by fwang** [comment]
Hi everyone, Frank from Seed here.

> Serverless Error: Trying to populate non string value into a string for variable ${self:custom.stage}. Please make sure the value of the property is a string

This usually happens when `${self:custom.stage}` is not defined in your serverless.yml. Make sure you have `stage` defined under the `custom` block, something like this:
```
custom:
  stage: ${opt:stage, self:provider.stage}
```

If you don't already have a `custom` block in your `serverless.yml`, add it to your serverless.yml above the `provider` block. If you do already have one, add the `stage: ${opt:stage, self:provider.stage}` to the block.

Be sure to watch out for indention. There are no spaces before `custom:`, and two spaces before `stage: ${opt:stage, self:provider.stage}`.

**Comment by AmoDinho** [comment]
@fwang Hey Frank, thanks for assisting!  🌟

**Comment by ltcrawshaw** [comment]
I'm getting a similar error: Serverless Error: Trying to populate non string value into a string for variable ${self:provider.environment.queu_name}. Please make sure the value of the property is a string.

This only appears in a comment, why is it breaking the build?

**Comment by fwang** [comment]
> ${provider.environment.queu_name}

`queu_name` seems to be misspelled? maybe?

**Comment by ltcrawshaw** [comment]
It was misspelled in one place. Didn't seem to be the issue though. There just seems to be a lot of overlooked details in the starter project and instructions. Thanks for the input though, Seed seems like an awesome tool

**Comment by ltcrawshaw** [comment]
> I had this too. In the serverless.yml file if you only include the `resources` provided in the example code, removing the default ones put there by the serverless installation, then the error should go away

Bluemagma612 is right, you have to delete the default resources and only include the two references to the listing and booking db files.

**Comment by audioe** [comment]
There doesn't seem to be an answer in here that's resolving the issue for me... I'm getting a number of variables that cannot be found:


 ```
Serverless Warning --------------------------------------
 
  A valid environment variable to satisfy the declaration 'env:NAME_OF_VAR' could not be found.
 
 
 Serverless Warning --------------------------------------
 
  A valid environment variable to satisfy the declaration 'env:ACCOUNT' could not be found.
 
 
 Serverless Warning --------------------------------------
 
  A valid service attribute to satisfy the declaration 'self:custom.stage' could not be found.
 
 
 Serverless Warning --------------------------------------
 
  A valid service attribute to satisfy the declaration 'self:custom.stage' could not be found.
 
 
 Serverless Warning --------------------------------------
 
  A valid service attribute to satisfy the declaration 'self:custom.tableDB' could not be found.
```
  
  Any ideas?  Dissapointing really as I'm only a couple pages in to this...

**Comment by AmoDinho** [comment]
@audioe Have you tried populating the environment variables in Seed? Also it seems like you've kept the variables from the Starter files too.

**Comment by audioe** [comment]
Thanks @AmoDinho for the reply.  Turns out that these errors are due to the default code that comes with the serverless.yml file. 
 I got these errors until I completed the next step in the guide ("Setting up the Tables"), which replaces a bunch of code in the serverless.yml file.

The resulting file which works looks like this:

```
# NOTE: update this with your service name
service: lunar-tour-api

# Use the serverless-webpack plugin to transpile ES6
plugins:
  - serverless-bundle
  - serverless-offline
  - serverless-dotenv-plugin

# serverless-webpack configuration
# Enable auto-packing of external modules
custom:
  stage: ${opt:stage, self:provider.stage}
  region: ${opt:region, self:provider.region}
  ListingsDB: ${self:custom.stage}-listings
  BookingsDB: ${self:custom.stage}-bookings
  tableThroughputs:
    prod: 1
    default: 1
  tableThroughput: ${self:custom.tableThroughputs.${self:custom.stage}, self:custom.tableThroughputs.default}
  serverless-offline:
    port: 4000
  bundle:
    linting: false

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: us-east-1
  profile: personalAccount
  environment:
    BookingsDB: ${self:custom.BookingsDB}
    ListingsDB: ${self:custom.ListingsDB}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:GetRecords
        - dynamodb:GetShardIterator
        - dynamodb:DescribeStream
        - dynamodb:ListStream

      Resource:
        - "Fn::GetAtt": [ListingsDB, Arn]
        - "Fn::GetAtt": [BookingsDB, Arn]

functions:
  graphql:
    handler: src/graphql.graphqlHandler
    environment:
      SLS_DEBUG: true
    events:
      - http:
          path: graphql
          method: post
          cors: true
          integration: lambda-proxy

      - http:
          path: graphql
          method: get
          cors: true
          integration: lambda-proxy

resources:
  - ${file(resources/listing-db.yml)}
  - ${file(resources/booking-db.yml)}
  #- ${file(resources/sqs-queue.yml)}
  #- ${file(resources/table.yml)}
  #- ${file(resources/s3-bucket.yml)}
  #- ${file(resources/cognito-identity-pool.yml)}
  #- ${file(resources/cognito-user-pool.yml)}
  # events:
  #     - sqs:
  #         arn: "arn:aws:sqs:${self:provider.environment.region}:${self:provider.environment.account}:${self:provider.environment.quque_name}-${self:provider.stage}"
  #         batchSize: 1
```

**Comment by AmoDinho** [comment]
Alright @audioe , have you been able to push the API with this new `serverless.yml` and is it working ? 😄

**Comment by audioe** [comment]
@AmoDinho Yes thanks.  It's worth mentioning also that the "Set up Tables" page needs a line adjusting slightly, the instructions state to add the following to the serverless.yml:

```
resources:
  - ${file(resources/listing-db.yml)}
  - ${file(resources/bookingDB.yml)}
```

This should be:
```
resources:
  - ${file(resources/listing-db.yml)}
  - ${file(resources/booking-db.yml)}
```

**Comment by AmoDinho** [comment]
@audioe  Thanks so much for that! I've just pushed the change. Also thanks for going through the guide! 🏆 

Please don't hesitate to open more issues or provide feedback as you continue to use the guide. It will go a long way to improve it for others. 🦖
